In [1]:
import numpy as np

In [3]:
# 2. Print the numpy version and the configuration (★☆☆)
print(np.__version__)
np.show_config()

1.24.4
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['C:/Users/prana/Untitled Folder 3/envs/nlp_env\\Library\\lib']
    include_dirs = ['C:/Users/prana/Untitled Folder 3/envs/nlp_env\\Library\\include']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['C:/Users/prana/Untitled Folder 3/envs/nlp_env\\Library\\lib']
    include_dirs = ['C:/Users/prana/Untitled Folder 3/envs/nlp_env\\Library\\include']
    language = f77
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['C:/Users/prana/Untitled Folder 3/envs/nlp_env\\Library\\lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['C:/Users/prana/Untitled Folder 3/en

In [5]:
# 3. Create a null vector of size 10 (★☆☆)
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
# 4. How to find the memory size of any array (★☆☆)
a = np.zeros((10,10))
print("%d bytes" % (a.size * a.itemsize))

800 bytes


In [13]:
# 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [15]:
# 7. Create a vector with values ranging from 10 to 49 (★☆☆)
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [21]:
# 8. Reverse a vector (first element becomes last) (★☆☆)
a = np.arange(10,50)
a = a[::-1]    #array[start:stop:step]
print(a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [23]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
a = np.arange(9).reshape((3,3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [27]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
a = np.array([1,2,0,0,4.0])
b = np.nonzero(a)
print(b)

(array([0, 1, 4], dtype=int64),)


In [29]:
# 11. Create a 3x3 identity matrix (★☆☆)
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
# 12. Create a 3x3x3 array with random values (★☆☆)
a = np.random.random((3,3,3))
print(a)

[[[0.70816389 0.25843588 0.59539982]
  [0.48674862 0.55714406 0.19793554]
  [0.63144386 0.94651462 0.22586475]]

 [[0.12698291 0.86825871 0.55431896]
  [0.46814944 0.17160551 0.38571564]
  [0.15172529 0.01873182 0.10498621]]

 [[0.2583906  0.70074709 0.24179033]
  [0.04833901 0.59351993 0.58939829]
  [0.24631055 0.44036794 0.05414158]]]


In [35]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
a = np.random.random((10,10))
b = a.min()
c = a.max()

print(a)
print(b)
print(c)

[[0.20688373 0.72402733 0.12690207 0.92699254 0.74952124 0.83313011
  0.63324373 0.15526398 0.57671045 0.95973237]
 [0.50519224 0.74382379 0.51642809 0.15416121 0.4621277  0.96734777
  0.5521766  0.19315869 0.00406613 0.48381034]
 [0.63795533 0.03433655 0.13631753 0.35220528 0.07385922 0.06064653
  0.4346262  0.99608816 0.90061034 0.82056528]
 [0.2649637  0.23704589 0.65798713 0.48814756 0.65524373 0.27605066
  0.5685241  0.83998955 0.76198103 0.63040258]
 [0.30733344 0.56488784 0.70967717 0.53158277 0.50519702 0.49160896
  0.07110251 0.29775084 0.88843352 0.2823922 ]
 [0.73452151 0.55829293 0.73838717 0.44837838 0.0086621  0.62550723
  0.94894588 0.01754439 0.32499556 0.58175395]
 [0.9294553  0.20426679 0.56782441 0.06813339 0.07192654 0.71013587
  0.33663871 0.07366158 0.38329988 0.99699968]
 [0.16441099 0.8797377  0.62608094 0.39470859 0.3102996  0.63358923
  0.77378824 0.93046238 0.65729997 0.81661494]
 [0.00941678 0.04259715 0.22586348 0.24130314 0.00386537 0.61901253
  0.03327051

In [37]:
# 14. Create a random vector of size 30 and find the mean value (★☆☆)
a = np.random.random(30)
b = a.mean()
print(a)
print(b)

[0.77767588 0.21194311 0.66845942 0.76909883 0.16431747 0.59834232
 0.68816175 0.12139769 0.17785155 0.34362632 0.77044273 0.22344745
 0.31608726 0.19084766 0.09511073 0.65688683 0.40425147 0.62229819
 0.13996903 0.29293949 0.06607316 0.44575381 0.87005797 0.00826604
 0.2998606  0.35341993 0.28780131 0.94156105 0.54992476 0.50380801]
0.41865606049785037


In [43]:
# 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
a = np.ones((10,10))

a[1:-1,1:-1] = 0   #array[start_row:end_row, start_col:end_col] = value
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [47]:
# 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
a = np.ones((6,6))
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [49]:
# Using fancy indexing
a[:,[0,-1]] = 0
a[[0,-1],:] = 0
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [53]:
# 17. What is the result of the following expression? (★☆☆)
0*np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])

True

In [55]:
0*np.nan

nan

In [57]:
np.nan == np.nan

False

In [59]:
np.inf > np.nan

False

In [61]:
np.nan - np.nan

nan

In [63]:
np.nan in set([np.nan])

True

In [69]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

a = np.diag(1+np.arange(4),k=-1)
print(a)



#1 + np.arange(4)
#Adds 1 to every element:


#1 + np.arange(4) → [1, 2, 3, 4]
#np.diag([1, 2, 3, 4], k=-1)
#📌 What np.diag() Does:
#It creates a matrix with values placed on a diagonal.

#k=0 → main diagonal

#k=1 → one above main diagonal

#k=-1 → one below main diagonal

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [73]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
a = np.zeros((8,8),dtype=int)
a[1::2,::2]=1     #array[row_start : row_stop : row_step , col_start : col_stop : col_step] = value
                  #Start from row 1 (2nd row), then every 2nd row (i.e. 1, 3, 5, 7)
                  #Start from column 0, then every 2nd column (i.e. 0, 2, 4, 6)
a[::2,1::2]=1     
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [77]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
a = print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [81]:
#Create a checkerboard 8x8 matrix using the tile function (★☆☆)
a = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(a)



#📌 What is np.tile()?
#🔹 Syntax:

#np.tile(array, reps)
#Parameter	Meaning
#array	The base pattern you want to repeat
#reps	A tuple: how many times to repeat along each axis



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [83]:
# 22. Normalize a 5x5 random matrix (★☆☆)
a = np.random.random((5,5))
a = (a - np.mean(a))/(np.std(a))
print(a)

[[-1.46012017  1.18878395 -1.17076999 -1.52422773 -0.33742235]
 [ 0.7673516   1.23832623  1.32542437  0.43641436 -0.68914848]
 [-0.80869038 -1.56858133  1.06791431  0.64279077  0.60920552]
 [-0.40970145  0.30784422  1.29079626 -0.24277903 -1.32742613]
 [ 0.78385741  0.80941812 -1.41383327 -0.43878682  0.92336   ]]


In [85]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#This code is used to create a custom data type in NumPy that represents a color using four values:

#R = Red

#G = Green

#B = Blue

#A = Alpha (transparency)

#All four are stored as 1 byte values (values between 0 and 255).

#What is np.dtype?
#dtype means data type in NumPy.

#It tells NumPy what kind of data will be stored.

#What is np.ubyte?
#✅ Full Form: NumPy Unsigned Byte
#It's a data type in NumPy.

#It is the same as: np.uint8 (unsigned 8-bit integer)

#It takes values from 0 to 255.

#Each value uses 1 byte of memory.

#🔴 Why "unsigned"?
#"Unsigned" means the value cannot be negative.

#So instead of going from -128 to 127 (signed), it goes from 0 to 255.

#What is np.uint?
#np.uint is not a specific size, and often means np.uint32 by default.

#It stands for Unsigned Integer.

#Unsigned = no negative values.

#But it’s better to use specific types like:

#np.uint8 → 1 byte (0 to 255)

#np.uint16 → 2 bytes (0 to 65535)

#np.uint32 → 4 bytes (large range)

#np.uint64 → 8 bytes (very large numbers)

#🔸 So:
#np.ubyte is the same as np.uint8 — both mean 8-bit unsigned integer.

In [87]:
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [89]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
a = np.matmul(np.ones((5,3)), np.ones((3,2)))
print(a)



#🔷 What is np.matmul?
#matmul stands for matrix multiplication.

#It performs real matrix multiplication, not element-by-element multiplication.

#In school math, matrix multiplication is:

#Multiply rows of the first matrix with columns of the second matrix.

#Add the results together.

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [93]:
#Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

a = np.arange(11)
a[(3<a) & (a<8)] *= -1
print(a)




#🧩 Step 3: Multiply In-Place

#a[...] *= -1
#This means: "multiply all selected elements by -1" — negate them, and do it in-place (i.e., modify the same array, not a copy).

#So:

#[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
#→ after negating 4, 5, 6, 7:
#[0, 1, 2, 3, -4, -5, -6, -7, 8, 9, 10]

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
