In [2]:
import pandas as pd
import numpy as np

In [3]:
# Pandas call string as an onject
country = ['USA','India','Pakistan','Nepal','Sri Lanka']
pd.Series(country)

0          USA
1        India
2     Pakistan
3        Nepal
4    Sri Lanka
dtype: object

In [4]:
# Integers
runs = [13,24,56,36,100]
pd.Series(runs)

0     13
1     24
2     56
3     36
4    100
dtype: int64

In [19]:
runs = [13,24,56,36,100]
runs_series = pd.Series(runs)

In [6]:
# Custom Index
marks = [67,57,87,100]
subjects = ['Maths','English','Science','Hindi']
pd.Series(marks,index=subject)

Maths       67
English     57
Science     87
Hindi      100
dtype: int64

In [9]:
marks = [67,57,87,100]
subjects = ['Maths','English','Science','Hindi']
pd.Series(marks,index=subjects,name='Pranay marks')

Maths       67
English     57
Science     87
Hindi      100
Name: Pranay marks, dtype: int64

In [10]:
marks = pd.Series(marks,index=subjects,name='Pranay marks')
marks

Maths       67
English     57
Science     87
Hindi      100
Name: Pranay marks, dtype: int64

In [13]:
marks = {
    'Maths':67,
    'English':57,
    'Science':89,
    'Hindi':100
}
marks_Series = pd.Series(marks,name='Pranay marks')
marks_Series

Maths       67
English     57
Science     89
Hindi      100
Name: Pranay marks, dtype: int64

In [14]:
marks_Series.dtype

dtype('int64')

In [15]:
marks_Series.name

'Pranay marks'

In [16]:
# is_unique
marks_Series.is_unique

True

In [17]:
pd.Series([1,1,2,3,4,5]).is_unique

False

In [18]:
# Index
marks_Series.index

Index(['Maths', 'English', 'Science', 'Hindi'], dtype='object')

In [20]:
runs_series.index

RangeIndex(start=0, stop=5, step=1)

In [22]:
# Values
marks_Series.values

array([ 67,  57,  89, 100], dtype=int64)

In [24]:
subs = pd.read_csv(r'C:\\Users\\prana\\Documents\\Python data\\subs.csv')
subs

Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [27]:
type(pd.read_csv(r'C:\\Users\\prana\\Documents\\Python data\\subs.csv'))

pandas.core.frame.DataFrame

In [28]:
subs = pd.read_csv(r'C:\\Users\\prana\\Documents\\Python data\\subs.csv',squeeze=True)
subs

C:\Users\prana\AppData\Local\Temp\ipykernel_22192\2592618712.py:1: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  subs = pd.read_csv(r'C:\\Users\\prana\\Documents\\Python data\\subs.csv',squeeze=True)


0       48
1       57
2       40
3       43
4       44
      ... 
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [29]:
type(pd.read_csv(r'C:\\Users\\prana\\Documents\\Python data\\subs.csv',squeeze=True))

C:\Users\prana\AppData\Local\Temp\ipykernel_22192\2167291365.py:1: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  type(pd.read_csv(r'C:\\Users\\prana\\Documents\\Python data\\subs.csv',squeeze=True))


pandas.core.series.Series

In [31]:
data = pd.read_csv(r'C:\\Users\\prana\\Documents\\Python data\\kohli_ipl.csv')
data

match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [42]:
df = pd.read_csv(r'C:\\Users\\prana\\Documents\\Python data\\kohli_ipl.csv',squeeze=True)
df

C:\Users\prana\AppData\Local\Temp\ipykernel_22192\3837354455.py:1: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  df = pd.read_csv(r'C:\\Users\\prana\\Documents\\Python data\\kohli_ipl.csv',squeeze=True)


match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [32]:
bl = pd.read_csv(r'C:\\Users\\prana\\Documents\\Python data\\bollywood.csv')
bl

movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [33]:
bl.sample()

movie    lead
851  Phoonk 2  Sudeep

In [34]:
bl.sample(5)

movie               lead
140                                Baazaar       Radhika Apte
1005                            Haal-e-Dil       Amita Pathak
693                      Yeh Khula Aasmaan         Anya Anand
901                                  Kaalo  Aditya Srivastava
626   Once Upon ay Time in Mumbai Dobaara!       Akshay Kumar

In [46]:
bl = pd.read_csv(r'C:\\Users\\prana\\Documents\\Python data\\bollywood.csv')
bl
movies = bl.squeeze()

In [47]:
type(movies)

pandas.core.frame.DataFrame

In [45]:
type(pd.read_csv(r'C:\\Users\\prana\\Documents\\Python data\\bollywood.csv', squeeze=True))

C:\Users\prana\AppData\Local\Temp\ipykernel_22192\376357624.py:1: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  type(pd.read_csv(r'C:\\Users\\prana\\Documents\\Python data\\bollywood.csv', squeeze=True))


pandas.core.frame.DataFrame

In [36]:
bl.sample(5)

movie          lead
1050             Apne    Dharmendra
764      Naughty @ 40       Govinda
1396     Sheen (film)   Tarun Arora
803   Tere Mere Phere  Vinay Pathak
565     Badlapur Boys   Annu Kapoor

In [38]:
# sort values in ASC order
data.sort_values(by='runs')

match_no  runs
86         87     0
210       211     0
206       207     0
205       206     0
90         91     0
..        ...   ...
163       164   100
119       120   100
122       123   108
125       126   109
127       128   113

[215 rows x 2 columns]

In [39]:
data.sort_values(by='runs',ascending=False)

match_no  runs
127       128   113
125       126   109
122       123   108
163       164   100
119       120   100
..        ...   ...
92         93     0
210       211     0
129       130     0
7           8     0
134       135     0

[215 rows x 2 columns]

In [43]:
df.sort_values(by='runs',ascending=False).head(1).values[0]

array([128, 113], dtype=int64)

In [44]:
df.sort_values(by='match_no',ascending=False).head(1).values[0]

array([215,   7], dtype=int64)

In [ ]:
# sort index
bl 