<a href="https://colab.research.google.com/github/Pranayshukla0610/basic-python/blob/main/Python_Numpy_Library_Practice_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Generate Employee IDs Using arange()

import numpy as np

employee_ids = np.arange(1001,1101)
print(employee_ids)

[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014
 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028
 1029 1030 1031 1032 1033 1034 1035 1036 1037 1038 1039 1040 1041 1042
 1043 1044 1045 1046 1047 1048 1049 1050 1051 1052 1053 1054 1055 1056
 1057 1058 1059 1060 1061 1062 1063 1064 1065 1066 1067 1068 1069 1070
 1071 1072 1073 1074 1075 1076 1077 1078 1079 1080 1081 1082 1083 1084
 1085 1086 1087 1088 1089 1090 1091 1092 1093 1094 1095 1096 1097 1098
 1099 1100]


In [3]:
#Generate time slots from 9 AM to 6 PM.

hours = np.arange(9,19)
print(hours)

[ 9 10 11 12 13 14 15 16 17 18]


In [4]:
#Generate Learning Rate Values Using linspace() between 0.001 and 0.1

learning_rates = np.linspace(0.001, 0.1, 10)
print(learning_rates)

[0.001 0.012 0.023 0.034 0.045 0.056 0.067 0.078 0.089 0.1  ]


In [5]:
#Generate 20 equally spaced temperatures between 20°C and 80°C

temperature = np.linspace(20,80,20)
print(temperature)

[20.         23.15789474 26.31578947 29.47368421 32.63157895 35.78947368
 38.94736842 42.10526316 45.26315789 48.42105263 51.57894737 54.73684211
 57.89473684 61.05263158 64.21052632 67.36842105 70.52631579 73.68421053
 76.84210526 80.        ]


In [6]:
#Generate Exponential Growth Values, create power of 10

growth = np.logspace(1, 10, 10)
print(growth)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10]


In [7]:
#Initialize a Neural Network Weight Matrix 50 neurons and 20 features

weights = np.zeros((50,20))
print(weights.shape)

(50, 20)


In [8]:
#Create attendance for 40 students for 5 days

attendance = np.ones((40,5),dtype=int)
print(attendance)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [9]:
#Initialize probabilities to 1 for 8x8

probabilities = np.ones((8,8))
print(probabilities)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [10]:
#Create Salary Matrix, Every employee gets 50000 in 20x12 salary matrix

salary = np.full((20,12),50000)
print(salary)

[[50000 50000 50000 50000 50000 50000 50000 50000 50000 50000 50000 50000]
 [50000 50000 50000 50000 50000 50000 50000 50000 50000 50000 50000 50000]
 [50000 50000 50000 50000 50000 50000 50000 50000 50000 50000 50000 50000]
 [50000 50000 50000 50000 50000 50000 50000 50000 50000 50000 50000 50000]
 [50000 50000 50000 50000 50000 50000 50000 50000 50000 50000 50000 50000]
 [50000 50000 50000 50000 50000 50000 50000 50000 50000 50000 50000 50000]
 [50000 50000 50000 50000 50000 50000 50000 50000 50000 50000 50000 50000]
 [50000 50000 50000 50000 50000 50000 50000 50000 50000 50000 50000 50000]
 [50000 50000 50000 50000 50000 50000 50000 50000 50000 50000 50000 50000]
 [50000 50000 50000 50000 50000 50000 50000 50000 50000 50000 50000 50000]
 [50000 50000 50000 50000 50000 50000 50000 50000 50000 50000 50000 50000]
 [50000 50000 50000 50000 50000 50000 50000 50000 50000 50000 50000 50000]
 [50000 50000 50000 50000 50000 50000 50000 50000 50000 50000 50000 50000]
 [50000 50000 50000 50000

In [12]:
#Every student initially gets 100, create 30 students 5 subjects

marks = np.full((30,5),100)
print(marks)

[[100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [13]:
#Identity Matrix for Matrix Multiplication

identity = np.eye(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
#Multiply matrix by identity matrix.

A = np.array([
    [2,3],
    [4,5]
])

I = np.eye(2)

result = A @ I
print(result)

[[2. 3.]
 [4. 5.]]


In [15]:
#Create Lower Triangular Matrix

matrix = np.tri(6)
print(matrix)

[[1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1.]]


In [16]:
#Generate Coordinate Grid

x = np.arange(1,6)
y = np.arange(1,6)

X, Y = np.meshgrid(x,y)

print("X")
print(X)

print("Y")
print(Y)

X
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
Y
[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]


In [17]:
#Generate Distance Matrix

import numpy as np

x = np.arange(-3,4)

y = np.arange(-3,4)

X,Y = np.meshgrid(x,y)

distance = np.sqrt(X**2 + Y**2)

print(np.round(distance,2))

[[4.24 3.61 3.16 3.   3.16 3.61 4.24]
 [3.61 2.83 2.24 2.   2.24 2.83 3.61]
 [3.16 2.24 1.41 1.   1.41 2.24 3.16]
 [3.   2.   1.   0.   1.   2.   3.  ]
 [3.16 2.24 1.41 1.   1.41 2.24 3.16]
 [3.61 2.83 2.24 2.   2.24 2.83 3.61]
 [4.24 3.61 3.16 3.   3.16 3.61 4.24]]
