<a href="https://colab.research.google.com/github/Pranayshukla0610/basic-python/blob/main/Python_Numpy_Library_Practice_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Find the Top 2 Highest Values in Every Row

import numpy as np

arr = np.array([
    [12, 45, 67, 23],
    [89, 34, 76, 90],
    [11, 56, 78, 44]
])

In [2]:
sorted_arr = np.sort(arr, axis=1)

top2 = sorted_arr[:,-2:][:,::-1]

print("Top 2 values of each row")
print(top2)

Top 2 values of each row
[[67 45]
 [90 89]
 [78 56]]


In [3]:
#Replace Maximum Value of Every Row with Zero

arr = np.array([
    [5, 8, 2],
    [9, 1, 7],
    [4, 6, 3]
])

In [4]:
row_max_index = np.argmax(arr, axis=1)

arr[np.arange(arr.shape[0]), row_max_index] = 0

print(arr)

[[5 0 2]
 [0 1 7]
 [4 0 3]]


In [5]:
import numpy as np

arr = np.array([
    [10, 200],
    [20, 300],
    [30, 400],
    [40, 500]
])

In [6]:
minimum = arr.min(axis=0)
maximum = arr.max(axis=0)

normalised = (arr - minimum) / (maximum - minimum)

print(normalised)

[[0.         0.        ]
 [0.33333333 0.33333333]
 [0.66666667 0.66666667]
 [1.         1.        ]]


In [7]:
#Find Duplicate Elements and Their Counts

import numpy as np

arr = np.array([2,5,3,2,7,5,9,2,5])

In [8]:
unique, counts = np.unique(arr, return_counts=True)

duplicates = unique[counts > 1]
duplicate_counts = counts[counts > 1]

print("Duplicate elements:", duplicates)
print("Their counts:", duplicate_counts)

Duplicate elements: [2 5]
Their counts: [3 3]


In [9]:
import numpy as np

A = np.array([2,5])

B = np.array([8,9])

In [10]:
distance = np.sqrt(np.sum((A - B)**2))
print("Distance:",distance)

Distance: 7.211102550927978


In [11]:
#Reverse Alternate Rows

import numpy as np

arr = np.arange(1,26).reshape(5,5)

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [12]:
arr = np.arange(1,26).reshape(5,5)

arr[1::2] = arr[1::2, ::-1]
print(arr)

[[ 1  2  3  4  5]
 [10  9  8  7  6]
 [11 12 13 14 15]
 [20 19 18 17 16]
 [21 22 23 24 25]]


In [13]:
#Find Common and Unique Elements

import numpy as np

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

common = np.intersect1d(arr1, arr2)
only_a = np.setdiff1d(arr1, arr2)
only_b = np.setdiff1d(arr2, arr1)

print("Common Element:",common)
print("Unique Element in A:", only_a)
print("Unique Element in B:", only_b)

Common Element: [3 4 5]
Unique Element in A: [1 2]
Unique Element in B: [6 7]


In [14]:
union = np.union1d(arr1, arr2)
print(union)

[1 2 3 4 5 6 7]


In [15]:
#Sort Matrix Based on Second Column

import numpy as np

arr = np.array([
    [101,90],
    [102,75],
    [103,95],
    [104,88]
])

In [16]:
sorted_arr = arr[arr[:,1].argsort()]
print(sorted_arr)

[[102  75]
 [104  88]
 [101  90]
 [103  95]]


In [17]:
import numpy as np

sales = np.array([
    [101,50000,6000],
    [102,65000,7000],
    [103,40000,5000],
    [104,70000,8000],
    [105,55000,6500]
])

# Columns:
# Employee_ID | Sales | Bonus

In [18]:
employee = sales[:,0]
sales_amount = sales[:,1]
bonus = sales[:,2]

print("Total Sales:",sales_amount.sum())
print("Average Sales:",sales_amount.mean())
print("Highest Sales:",sales_amount.max())
print("Lowest Sales:",sales_amount.min())

Total Sales: 280000
Average Sales: 56000.0
Highest Sales: 70000
Lowest Sales: 40000


In [19]:
highest_employee = employee[np.argmax(sales_amount)]
print("Highest Sales Employee:",highest_employee)

Highest Sales Employee: 104


In [20]:
print("Total bonus:",bonus.sum())
bonus_percent = np.round((bonus/sales_amount)*100,2)
print("Bonus Percentage:",bonus_percent)

Total bonus: 32500
Bonus Percentage: [12.   10.77 12.5  11.43 11.82]


In [21]:
rank = sales_amount.argsort()[::-1]
print("Sales Ranking:")
print(sales[rank])

Sales Ranking:
[[  104 70000  8000]
 [  102 65000  7000]
 [  105 55000  6500]
 [  101 50000  6000]
 [  103 40000  5000]]


In [22]:
above_average = sales[sales_amount > sales_amount.mean()]
print("Employee Above Average Sales:")
print(above_average)

Employee Above Average Sales:
[[  102 65000  7000]
 [  104 70000  8000]]


In [23]:
cumulative = np.cumsum(sales_amount)
print("Cumulative Sales:",cumulative)

Cumulative Sales: [ 50000 115000 155000 225000 280000]


In [24]:
#Calculate Row-wise Percentage Contribution

import numpy as np

sales = np.array([
    [100,200,300],
    [150,250,100],
    [400,300,300]
])

In [25]:
row_total = sales.sum(axis=1, keepdims=True)
percentage = (sales / row_total) * 100
print(np.round(percentage,2))

[[16.67 33.33 50.  ]
 [30.   50.   20.  ]
 [40.   30.   30.  ]]


In [26]:
#Sort Matrix Based on Second Column

import numpy as np

arr = np.array([
    [101,90],
    [102,75],
    [103,95],
    [104,88]
])

In [27]:
sorted_arr = arr[arr[:,1].argsort()]
print(sorted_arr)

[[102  75]
 [104  88]
 [101  90]
 [103  95]]
